print("Welcome to the interactive personal data collector")
name=input("enter your name:")
age=int(input("enter your age:"))
height=float(input("enter your height in meter"))
num=int(input("enter your favourite number:"))
print("thank you ! here is the information that we collected")
print('Name:',name)
print(type(name))
print(id(name))
print("")
print("age",age)
print(type(age))
print(id(age))
print("")
print('height',height)
print(type(height))
print(id(height))
print("")
print('num',num)
print(type(num))
print(id(num))
age1=2026-age
print("your birth year is approximate ",age1,"base on your given data")
print("thank you for your personal data" )